### ISSUE TITLE
api.ai config?

### ISSUE THREAD

**Issue by mvillarejo** [hokus15/home-assistant-config#1]
Hello! I'm really impress with your setups and automations, specially the on/off config for api.ai, any chance you can share your application json config? it'll be great to see that.

(En español sería perfecto) 👍

**Comment by hokus15** [comment]
It's still work in progress. Aunque está en español ;)
[Home-Assistant.zip](https://github.com/hokus15/home-assistant-config/files/959833/Home-Assistant.zip)
I've been only playing with api.ai since two weeks ago so any best practice advise is welcome. Any doubt or question let me know.

**Comment by mvillarejo** [comment]
thanks! my ony advise would be... get a google home or alexa :D
